Tmux status bar adjustment, vimrc adjustments (cscope)

diff --git a/version_cmp b/version_cmp
--- a/version_cmp
+++ b/version_cmp
@@ -10,10 +10,6 @@ cmp="$(sed -r 's/'"$regex"'/\3/' <<< "$1")"
   echo "Could not parse: $1" >&2 &&
   exit 1
 
-[[ ! "$cmp" =~ ^(\<|\<=|\==|\=|\>=|\>)$ ]] &&
-  echo "Invalid comparator: $cmp" >&2 &&
-  exit 1
-
 if [[ $cmp == "<" ]]; then
   version_lt "$v1" "$v2" &&
     echo 1 ||
@@ -30,9 +26,12 @@ elif [[ $cmp == ">=" ]]; then
   version_lte "$v2" "$v1" &&
     echo 1 ||
     echo 0
-else
+elif [[ $cmp == ">" ]]; then
   version_lt "$v2" "$v1" &&
     echo 1 ||
     echo 0
+else
+  echo "Invalid comparator: $cmp" >&2 &&
+  exit 1
 fi
 
